
#include <string.h>
#include "Handler.h"

//多语言版支持
typedef struct  _LocalLanguageRes{
        char* ctext;
        char* etext;
}LocalLanguageRes;

static LocalLanguageRes g_language_res[]={
        {"系统正在启动...","Starting..."},
        {"呼叫","Call"},
        {"监视","Monitor"},
        {"图文","Messages"},
        {"在家","Home"},
        {"离家","Outside"},
        {"服务","Service"},
        {"智联","Smart Home"},
        {"设置","Settings"},
        {"帮助","Help"},
        {"电梯","Lift"},
        {"呼叫中心","Guard"},
        {"呼叫住户","Tenant"},
        {"召唤电梯","Lift"},
        {"大堂经理","Duty Manager"},
        {"正在呼叫中心...","Calling..."},
        {"正在连接中...","Connecting..."},
        {"开始通话...","Speaking..."},
        {"请输入房号","Input room No."},
        {"呼叫格式","Dial format"},
        {"请输入13位房间编号","Input Room ID"},
        {"按'#'呼叫,按'*'退格!","'#' for call,'*' for backspace!"},
        {"请选择监视点","Please select"},
        {"报警记录","Alarm Record"},
        {"语音信箱","Voice Box"},
        {"图片","Picture"},
        {"短消息","Message"},
        {"没有任何报警日志...","No  alarm record..."},
        {"程序出现错误...","Program Error"},
        {"没有图片...","No picture..."},
        {"没有短消息...","No message..."},
        {"没有语音留言...","No voice message..."},
        {"维修求助","Maintenance"},
        {"维修","Maintenance"},
        {"费用查询","Fee Check"},
        {"铃声下载","Ring Download"},
        {"便民服务","Living Message"},
        {"家庭留言","Voice Message"},
        {"服务中心","Service Center"},
        {"项目","Option"},
        {"供电系统故障","Electric"},
        {"供水系统故障","Water"},
        {"厨卫家居故障","Kitchen"},
        {"供气系统故障","Gas"},
        {"生活用水费","Water"},
        {"电费","Electricity"},
        {"燃气费","Gas"},
        {"管理费","Management fee"},
        {"饮用水费","Drinking Water"},
        {"取暖费","Heating"},
        {"小门口机","Front door station"},
        {"数字小门口机","IP Front door station"},
        {"主围墙机","Entrance Station"},
        {"主门口机","Main Gate Station"},
        {"住户","Tenant"},
        {"门口机","Gate Station"},
        {"摄像头一","Camera 1"},
        {"摄像头二","Camera 2"},
        {"摄像头三","Camera 3"},
        {"正在查询...","Accessing.."},
        {"留言倒计时","Count Down"},
        {"秒","s"},
        {"留言录制完毕!","Voice record finished !"},
        {"情景控制","Scene"},
        {"室内控制","Device Control"},
        {"会客","Guest"},
        {"就餐","Dinner"},
        {"影院","Cinema"},
        {"就寝","Sleeping"},
        {"温馨","Warm"},
        {"夜起","Night Light"},
        {"晨起","Get up"},
        {"闹钟","Alarm Clock"},
        {"请选择房间类别","Room"},
        {"请选择房间","Room No."},
        {"请选择电器类别","Device"},
        {"请选择电器","Device No."},
        {"卧室","Bedroom"},
        {"主卧室","Main Bedroom"},
        {"卧室一","Bedroom NO.1"},
        {"卧室二","Bedroom NO.2"},
        {"卧室三","Bedroom NO.3"},
        {"卧室四","Bedroom NO.4"},
        {"卧室五","Bedroom NO.5"},
        {"卧室六","Bedroom NO.6"},
        {"卧室七","Bedroom NO.7"},
        {"卧室八","Bedroom NO.8"},
        {"卧室九","Bedroom NO.9"},
        {"客厅","Living room"},
        {"客厅一","Living room NO.1"},
        {"客厅二","Living room NO.2"},
        {"客厅三","Living room NO.3"},
        {"客厅四","Living room NO.4"},
        {"客厅五","Living room NO.5"},
        {"客厅六","Living room NO.6"},
        {"客厅七","Living room NO.7"},
        {"客厅八","Living room NO.8"},
        {"客厅九","Living room NO.9"},
        {"餐厅","Dinning room"},
        {"餐厅一","Dinning room NO.1"},
        {"餐厅二","Dinning room NO.2"},
        {"餐厅三","Dinning room NO.3"},
        {"餐厅四","Dinning room NO.4"},
        {"餐厅五","Dinning room NO.5"},
        {"餐厅六","Dinning room NO.6"},
        {"餐厅七","Dinning room NO.7"},
        {"餐厅八","Dinning room NO.8"},
        {"餐厅九","Dinning room NO.9"},
        {"书房","Book Room"},
        {"书房一","Book Room NO.1"},
        {"书房二","Book Room NO.2"},
        {"书房三","Book Room NO.3"},
        {"书房四","Book Room NO.4"},
        {"书房五","Book Room NO.5"},
        {"书房六","Book Room NO.6"},
        {"书房七","Book Room NO.7"},
        {"书房八","Book Room NO.8"},
        {"书房九","Book Room NO.9"},
        {"厨房","Kitchen"},
        {"厨房一","Kitchen NO.1"},
        {"厨房二","Kitchen NO.2"},
        {"厨房三","Kitchen NO.3"},
        {"厨房四","Kitchen NO.4"},
        {"厨房五","Kitchen NO.5"},
        {"厨房六","Kitchen NO.6"},
        {"厨房七","Kitchen NO.7"},
        {"厨房八","Kitchen NO.8"},
        {"厨房九","Kitchen NO.9"},
        {"卫生间","Bathroom"},
        {"卫生间一","Bathroom NO.1"},
        {"卫生间二","Bathroom NO.2"},
        {"卫生间三","Bathroom NO.3"},
        {"卫生间四","Bathroom NO.4"},
        {"卫生间五","Bathroom NO.5"},
        {"卫生间六","Bathroom NO.6"},
        {"卫生间七","Bathroom NO.7"},
        {"卫生间八","Bathroom NO.8"},
        {"卫生间九","Bathroom NO.9"},
        {"阳台","Balcony"},
        {"阳台一","Balcony NO.1"},
        {"阳台二","Balcony NO.2"},
        {"阳台三","Balcony NO.3"},
        {"阳台四","Balcony NO.4"},
        {"阳台五","Balcony NO.5"},
        {"阳台六","Balcony NO.6"},
        {"阳台七","Balcony NO.7"},
        {"阳台八","Balcony NO.8"},
        {"阳台九","Balcony NO.9"},
        {"自定义","User-defined"},
        {"自定义一","User-defined NO.1"},
        {"自定义二","User-defined NO.2"},
        {"自定义三","User-defined NO.3"},
        {"自定义四","User-defined NO.4"},
        {"自定义五","User-defined NO.5"},
        {"自定义六","User-defined NO.6"},
        {"自定义七","User-defined NO.7"},
        {"自定义八","User-defined NO.8"},
        {"自定义九","User-defined NO.9"},
        {"自定义十","User-defined NO.10"},
        {"灯光","Light"},
        {"灯光一","Light NO.1"},
        {"灯光二","Light NO.2"},
        {"灯光三","Light NO.3"},
        {"灯光四","Light NO.4"},
        {"灯光五","Light NO.5"},
        {"灯光六","Light NO.6"},
        {"灯光七","Light NO.7"},
        {"灯光八","Light NO.8"},
        {"灯光九","Light NO.9"},
        {"灯光十","Light NO.10"},
        {"窗帘","Curtain"},
        {"窗帘一","Curtain NO.1"},
        {"窗帘二","Curtain NO.2"},
        {"窗帘三","Curtain NO.3"},
        {"窗帘四","Curtain NO.4"},
        {"窗帘五","Curtain NO.5"},
        {"窗帘六","Curtain NO.6"},
        {"窗帘七","Curtain NO.7"},
        {"窗帘八","Curtain NO.8"},
        {"窗帘九","Curtain NO.9"},
        {"窗帘十","Curtain NO.10"},
        {"电视","TV"},
        {"电视一","TV NO.1"},
        {"电视二","TV NO.2"},
        {"电视三","TV NO.3"},
        {"电视四","TV NO.4"},
        {"电视五","TV NO.5"},
        {"电视六","TV NO.6"},
        {"电视七","TV NO.7"},
        {"电视八","TV NO.8"},
        {"电视九","TV NO.9"},
        {"电视十","TV NO.10"},
        {"空调","Air-conditioner"},
        {"空调一","Air-conditioner NO.1"},
        {"空调二","Air-conditioner NO.2"},
        {"空调三","Air-conditioner NO.3"},
        {"空调四","Air-conditioner NO.4"},
        {"空调五","Air-conditioner NO.6"},
        {"空调六","Air-conditioner NO.5"},
        {"空调七","Air-conditioner NO.7"},
        {"空调八","Air-conditioner NO.8"},
        {"空调九","Air-conditioner NO.9"},
        {"空调十","Air-conditioner NO.10"},
        {"DVD","DVD"},
        {"DVD一","DVD NO.1"},
        {"DVD二","DVD NO.2"},
        {"DVD三","DVD NO.3"},
        {"DVD四","DVD NO.4"},
        {"DVD五","DVD NO.5"},
        {"DVD六","DVD NO.6"},
        {"DVD七","DVD NO.7"},
        {"DVD八","DVD NO.8"},
        {"DVD九","DVD NO.9"},
        {"DVD十","DVD NO.10"},
        {"插座","Socket"},
        {"插座一","Socket NO.1"},
        {"插座二","Socket NO.2"},
        {"插座三","Socket NO.3"},
        {"插座四","Socket NO.4"},
        {"插座五","Socket NO.5"},
        {"插座六","Socket NO.6"},
        {"插座七","Socket NO.7"},
        {"插座八","Socket NO.8"},
        {"插座九","Socket NO.9"},
        {"插座十","Socket NO.10"},
        {"感应器","Inductor"},         //
        {"温度感应器","Temperature"},    //
        {"湿度感应器","Humidity"},  //
        {"移动感应器","Shift"},    //
        {"光照感应器","Illumination"},    //
        {"烟雾感应器","Smog"},        //
        {"一氧化碳感应器","Carbon monoxide"},   //
        {"二氧化碳感应器","CO2"},   //
        {"风力感应器","Anemometry"},     //
        {"雨量感应器","Rain gauge"},  //
        {"其他感应器","Other"},     //
        {"关","OFF"},
        {"开","ON"},
        {"强","Strong"},
        {"弱","Weak"},
        {"解锁","Unlock"},
        {"锁定","Lock"},
        {"停","Stop"},
        {"频道+","Channel +"},
        {"频道-","Channel -"},
        {"音量+","Volume +"},
        {"音量-","Volume -"},
        {"22度","22 ℃"},
        {"25度","25 ℃"},
        {"27度","27 ℃"},
        {"28度","28 ℃"},
        {"29度","29 ℃"},
        {"密码","Password"},
        {"安防","Alarm"},
        {"铃声","Ring"},
        {"系统","System"},
        {"时间校准","Time Adjustment"},
        {"屏幕校准","Screen Adjustment"},
        {"升级","Upgrade"},
        {"镜像升级","Image Upgrade"},
        {"应用升级","App Upgrade"},
        {"本机设置","Basic setting"},
        {"时间已经和中心校准!","Time correct!"},
        {"请输入旧密码:","Input old password"},
        {"请输入新密码:","Input new password"},
        {"请再次输入新密码:","Input again"},
        {"提示:按'*'退格，按'#'确认","Note:'*'for backspace,'#'for confirm"},
        {"请输入密码:","Input password"},
        {"防区启用","Alarm Zone"},
        {"布/撤防","Arm/Disarm"},
        {"请选择需要启动的防区","Select the zones"},
        {"防区","Zone"},
        {"全部布防","Arm all"},
        {"全部撤防","Disarm all"},
        {"铃声设置","Ring"},
        {"中心呼叫铃声","Guard"},
        {"围墙机呼叫铃声","Entrance Station"},
        {"门口机呼叫铃声","Gate Station"},
        {"小门口机呼叫铃声","Front door station"},
        {"户户通铃声","Door-to-Door"},
        {"报警铃声","Alarm"},
        {"短信铃声","Message "},
        {"闹钟铃声","Clock"},
        {"没有已下载的铃声!","No rings!"},
        {"情景配置","Scene Setting"},
        {"室内配置","Indoor Setting"},
        {"定时配置","Profile Timer"},
        {"智联对码","Device Setting"},
        {"远程开","Remote ON"},
        {"远程关","Remote OFF"},
        {"智联网关ID:","Controller ID:"},
        {"智联网关IP:","Controller IP:"},
        {"智联对码:","Register code:"},
        {"手机号码","Phone NO."},
        {"任务计划，每天最多可选择6个情景执行，输入的时间为24小时制","Task plan, 6 options everyday, time format is 24H"},
        {"执行","Activate"},
        {"全部取消","Cancel"},
        {"增加","Add"},
        {"停止","Stop"},
        {"时","h"},
        {"会客模式","Guest"},
        {"就餐模式","Dinner"},
        {"影院模式","Cinema"},
        {"就寝模式","Sleeping"},
        {"温馨模式","Warm"},
        {"在家模式","Home"},
        {"离家模式","Outside"},
        {"夜起模式","Night Light"},
        {"晨起模式","Get up"},
        {"自定义模式","User-defined"},
        {"分","m"},
        {"年","year"},
        {"月","month"},
        {"日","day"},
        {"秒","s"},
        {"设备类型:","Devices:"},
        {"智能开关","Switch"},
        {"智能插座和开关","Socket "},
        {"智能红外转发器","Infrared "},
        {"智能窗帘控制器","Curtain "},
        {"智能灯光控制器","Lighting"},
        {"宠物喂养器","Pet-feeder"},
        {"电脑类","PC"},
        {"智能遥控器","Remote-controller"},
        {"智能终端","PDA"},
        {"智能插座","Smart socket"},
        {"ECB设备","ECB"},
        {"设备地址:","Address:"},
        {"RIU类型:","R_type:"},
        {"RIU地址:","R_add:"},
        {"设备子地址:","sub:"},
        {"RIU编号:","R_ID:"},
        {"红外类型:","I_type:"},
        {"通路地址:","Raddr:"},//
        {"红外控制","IR_Ctrl"},//
        {"关联防区:","Zone:"},//
        {"系统信息","System info"},
        {"系统状态","System State"},
        {"子网掩码","Subnet Mask"},
        {"网关","Gateway"},
        {"中心","Admin PC"},
        {"中心报警","Alarm PC alarm"},
        {"本机软件版本","Version"},
        {"本机状态: 活动","State: active"},
        {"可用的Flash空间","Available Flash space"},
        {"已使用的Flash空间","Used space"},
        {"本机按键音启用","Key tone: ON"},
        {"本机按键音关闭","Key tone: OFF"},
        {"本机智联模块关闭","Smart Home: Disabled"},
        {"本机智联模块启用","Smart Home: Enabled"},
        {"本机屏幕保护关闭","Screen saver: OFF"},
        {"本机屏幕保护启用","Screen saver: ON"},
        {"本机未托管","Divert: OFF "},
        {"本机已托管","Divert: ON "},
        {"本机未设置免打扰","No-disturb: OFF"},
        {"本机已设置免打扰","No-disturb: ON"},
        {"本机自动抓拍关闭","Auto-snapshot: OFF"},
        {"本机自动抓拍启用","Auto-snapshot: ON"},
        {"本机远程控制关闭","Remote-control: OFF"},
        {"本机远程控制启用","Remote-control: ON"},
        {"配置信息"," setting"},
        {"状态","Status"},
        {"附加功能","Appendix Function"},
        {"托管","Divert ON"},
        {"取消托管","Divert OFF"},
        {"色彩管理","Color"},
        {"音量调节","Volume"},
        {"免打扰","No-disturb ON"},
        {"取消免打扰","No-disturb OFF"},
        {"延时设置","Delay Setting"},
        {"网络配置","Network Setting"},
        {"恢复出厂设置","Restore Settings"},
        {"是否启动自动抓拍","Snapshot"},
        {"是否启动按键提示音","key tone"},
        {"是否启动屏保","Screen saver"},
        {"是否挂接模拟分机","Enable Analogous door phone"},
        {"小时","hour"},
        {"分钟","minute"},
        {"(提示:默认为12小时,时间不能超过99小时,59分)","(Tips:Default is 12H, no exceed 99H59M)"},
        {"请输入托管的持续时间:","Input call divert duration time"},
        {"请输入免打扰持续时间:","Input duration time for No-disturbance"},
        {"持续时间为","Duration"},
        {"视频亮度","Video Brightness"},
        {"视频对比度","Video Contrast"},
        {"视频饱和度","Video Saturation"},
        {"铃声音量","Ring Volume"},
        {"高音","High Volume"},
        {"低音","Low Volume"},
        {"通话音量","Speaking Volume"},
        {"报警音量","Alarm Volume"},
        {"麦克风音量","Microphone Volume"},
        {"请输入响铃持续时间(35-60)秒:","Ring duration(35-60)S:"},
        {"请输入布防延时时间(1-255)秒:","Arm delay(1-255)S:"},
        {"请输入报警声持续时间(30-300)秒:","Alarm duration(30-300)S:"},
        {"请输入上报延时时间(1-255)秒:","Upload delay(1-255)S:"},
        {"自动配置","Automatic"},
        {"手动配置","Manual"},
        {"请输入15位房间编号(2位区号-3位栋号-2位单元号-3位层号-3位房号-2位分机编号)","Input 15-digit ID.(G(2)-B(3)-U(2)-F(3)-R(3)-N(2))"},
        {"区号:","   G:"},
        {"栋号:","  B:"},
        {"单元号:","   U:"},
        {"层号:","   F:"},
        {"房间号:","  R:"},
        {"分机编号:","   D:"},
        {"房间","Room"},
        {"区","G"},
        {"栋","B"},
        {"单元","U"},
        {"层","F"},
        {"房","R"},
        {"编号","N"},
        {"管理机","Guard Station"},
        {"备用电梯","Standby Lift"},
        {"备用电梯1","Standby Lift 1"},
        {"提示：按'*'退格，按'#' 输入'.'","'*' for backspace,'#' for '.'"},
        {"恢复出厂设置.","Restore to factory settings"},
        {"本操作会导致丢失个人资料和数据,","This operation will clear personal data,"},
        {"而且所有设置将恢复到出厂设置.","all settings will restore to factory default."},
        {"您要继续吗？请输入密码","Input password to continue..."},
        {"按'#'确认","Press '#' to confirm"},
        {"暂无可供下载的铃声,请按‘返回’键回到上一级!","No rings provided, back to previous menu!"},
        {"暂无可供查询的数据,请按‘返回’键回到上一级!","No information, back to previous menu!"},
        {"中心呼叫您...","Guard calling-in"},
        {"SIP客户端呼叫您...","SIP calling-in"},
        {"响铃中...","Ring..."},
        {"请检查网络配置及网线!","Network error !"},
        {"留言播放完毕!","Finished playing voice message!"},
        {"没有任何联系人...","No Contacts..."},
        {"单独控制防区状态","Control zone status separately"},
        {"离家防区状态",""},
        {"是否启用远程控制防区和家居","Enable Remote control Alarm zones and home device? "},
        {"是否启用自动抓拍","Enable auto-snapshot?"},
        {"正在呼叫对方...","Calling..."},
        {"暂无帮助信息，正请求中心配置...","No information provided and request Admin PC to configure ..."},
        {"没有列表...","No list..."},
        {"用户确认","Confirm"},//user to confirm

        {"对方繁忙!","Busy line!"},
        {"中心繁忙!","Guard is busy !"},
        {"本机繁忙!","Busy line !"},
        {"分机繁忙!","Busy line !"},
        {"对方挂机或者忙碌","Hang up or Busy line!"},
        {"网络不通!","Connection failed!"},
        {"中心未配置服务内容!","No service provided !"},
        {"配置信息已经设置!","Succeeded!"},
        {"铃声下载失败!","Failed !"},
        {"下载铃声中...","Downloading…."},
        {"正在保存数据...","Saving..."},
        {"下载完成!","Completed!"},
        {"播放中...,按确认停止!","Press 'confirm' for Stop!"},
        {"如果要下载，请按下载按钮!","Press 'Download' for saving!"},
        {"维修请求已经受理!","Accepted maintenance request!"},
        {"升级成功,5s后自动重启","Update succeeded, restart after 5s"},
        {"校屏成功","Screen rectified!"},
        {"中心远程重启分机","Remote restart"},
        {"系统正在升级","Updating"},
        {"系统升级失败","Update failed"},
        {"从分机请求同步","Sub door phone requests Sync"},
        {"正在格式化...","Formatting..."},
        {"格式化完毕!","Succeeded!"},
        {"屏幕已经校准!","Screen rectified!"},
        {"屏幕校准失败!","Screen rectified failed!"},
        {"你确定要清空所有留言","Clear all messages?"},
        {"你确定要删除该留言","Delete the message?"},
        {"你确定要清空联系人簿","Clear all contact list?"},
        {"你确定要删除该联系人","Delete the contact?"},
        {"确定和中心时间校准?","Calibrate time?"},
        {"确定要校正屏幕吗?","Confirm to calibrate screen?"},
        {"输入错误，请重新输入!"," Wrong input, Please input again!"},
        {"未设置日期，请校对系统日期!","Date has not be set, check please. "},
        {"未增加情景计划!","Has not add more Scene"},
        {"确定重置防区!","Confirm to reset alarm zone!"},
        {"确定启用选定防区!","Confirm to enable the selected zone!"},
        {"当前非‘在家’模式，只有'在家'模式才能单独控制防区",""},
        {"铃声已经下载，请到铃声设置中试听!","Completed, try audition!"},
        {"请稍等，正在缓冲...","Buffering..."},
        {"该铃声已经下载","The ring exists already"},
        {"确定要下载!","Confirm to download!"},
        {"确定要设置当前铃声为","Set the ring as "},
        {"你确定要清空所有铃声","Clear all rings?"},
        {"你确定要删除该铃声","Delete the ring?"},
        {"锁定状态,不能删除","Locked, cannot delete!"},
        {"默认铃声,不能删除","Default ring, cannot delete!"},
        {"你确定要清空所有图片","Clear all pictures?"},
        {"你确定要删除该图片","Delete the picture?"},
        {"你确定要删除该歌曲","Delete the music?"},
        {"密码错误!!!","Wrong Password !"},
        {"已经恢复出厂设置,5秒后重启","Succeeded, restart after 5s"},
        {"旧密码错误，再次输入？","Wrong password, input again?"},
        {"两次输入新密码不同，再次输入？","Not match, input again ?"},
        {"修改密码成功！","Succeeded!"},
        {"你确定要清空所有的短消息","Clear all messages?"},
        {"你确定要删除该短消息","Delete the message?"},
        {"确定要修改网络配置？","Confirm to modify network settings?"},
        {"修改配置中...","Modifying..."},
        {"修改网络配置失败","Failed !"},
        {"修改网络配置成功","Succeeded !"},
        {"你确定要修改房间编号？","Confirm to modify ID?"},
        {"修改房间号成功,5秒后系统重启!","Succeeded, restart after 5s!"},
        {"正在向中心请求配置....","Request Admin PC to configure ..."},
        {"离家状态下,防区将设防,电源将关闭.确定要选择离家模式吗?","During Scene 'Outside', all zone are armed , and power off , confirm ? "},
        {"控制'在家'情景...","Control 'Home' scene..."},
        {"控制'离家'情景...","Control 'Outside' scene..."},
        {"确定要增加到地址簿?","Add it to contact list?"},
        {"不能自己呼叫自己!","Can’t call yourself"},
        {"无此从分机!","Not found!"},
        {"进入调试模式","Enter Debug mode"},
        {"进入正常模式","Enter normal mode"},
        {"启动屏幕保护","Activate screen saver"},
        {"取消屏幕保护","Cancel screen saver"},
        {"启动中心协商","Activate center negotiate"},
        {"取消中心协商","Cancel center negotiate"},
        {"正在清除数据，并恢复默认设置","Clearing data and return to default"},
        {"清除，并恢复默认设置成功","Delete, and return to default setting successfully"},
        {"设置抓拍图片质量成功","Picture quantity set successfully!"},
        {"设置录像帧率成功！","Image max quantity,set successfully"},
        {"设置抓拍图片最大数量成功！","Image max quantity is set."},
        {"正在启动/停止SIP服务...","Start/stop SIP service"},
        {"启动/停止SIP成功！","Start/stop SIP Succeed!"},
        {"设置音频参数G711,16K,20ms！","Set audio parameter G711,16K,20ms!"},
        {"设置音频参数G711,8K,40ms！","Set audio parameter G711,8K,40ms!"},
        {"确定要格式化Flash?","Confirm to format Flash?"},
        {"设置增加智联模块","Add smart home module"},
        {"设置取消智联模块","Cancel smart home module"},
        {"该房号不存在!","Not found"},
        {"呼叫的地址不对","Not found"},
        {"监视地址不对","Not found"},
        {"设置完毕!","Completed!"},
        {"你确定要清空所有日志","Clear all logs?"},
        {"你确定要删除该日志","Delete the log?"},
        {"已经设置托管,是否取消托管设置?","Divert is set!Cancel it?"},

        {"您已经设置了免打扰,设置托管时,将强制取消免打扰!","No-disturb is set !No-disturb will be off when setting divert ."},
        {"已经设置免打扰,是否取消免打扰设置?","No-disturb is set! Cancel it?"},
        {"您已经设置了托管,设置免打扰时,将强制取消托管!","Divert is set !It will cancel divert when setting No-disturb."},

        {"响铃时间设置完毕!","Ring time setting completed!"},
        {"布防延时时间设置完毕!","Arm delay setting completed!"},
        {"上报延时时间设置完毕!","Upload time delay setting completed!"},
        {"报警声持续时间设置完毕!","Alarm ring time setting completed!"},
        {"设置托管成功!","Succeeded !"},
        {"设置免打扰成功","Succeeded !"},
        {"取消免打扰设置成功!","Cancel Successful!"},
        {"取消托管设置成功!","Cancel Successful!"},
        {"保存设置成功!","Saved !"},
        {"清空旧的配置表?","Clear all setting tables ?"},
        {"正在清空配置...","Clearing..."},
        {"正在清空情景配置...","Clearing all scene settings"},
        {"清空失败!","Failed !"},
        {"清空成功!","Succeeded !"},
        {"清空旧的'会客'情景配置?","Clear former Guest Scene!"},
        {"清空旧的'就餐'情景配置?","Clear former Dinner Scene!"},
        {"清空旧的'影院'情景配置?","Clear former Cinema Scene!"},
        {"清空旧的'就寝'情景配置?","Clear former Sleeping Scene!"},
        {"清空旧的'温馨'情景配置?","Clear former Warm Scene!"},
        {"清空旧的'在家'情景配置?","Clear former Home Scene!"},
        {"清空旧的'离家'情景配置?","Clear former Absence  Scene!"},
        {"正在设置设备地址...","Setting device address..."},
        {"设置设备地址成功...","Succeed !"},
        {"设置设备地址失败...","Failed !"},
        {"红外学习中...","Studying Infrared devices..."},
        {"学习红外成功","Succeed !"},
        {"学习红外失败","Failed !"},
        {"配置成功","Succeeded !"},
        {"配置失败","Failed !"},
        {"配置情景模式中...","Configuring profile..."},
        {"控制家居中...","Controlling..."},
        {"控制成功","Succeeded!"},
        {"控制失败","Failed !"},
        {"正在设置RIU的系统ID...","Setting RIU system ID..."},
        {"正在控制'会客'情景...","Control Guest scene"},
        {"正在控制'就餐'情景...","Control Dinner scene"},
        {"正在控制'影院'情景...","Control Cinema scene"},
        {"正在控制'就寝'情景...","Control Sleeping scene"},
        {"正在控制'温馨'情景...","Control Warm scene"},
        {"正在控制'在家'情景...","Control Home scene"},
        {"正在控制'离家'情景...","Control Outside scene"},
        {"正在控制'夜起'情景...","Control Night Light scene"},
        {"正在控制'晨起'情景...","Control Get up scene"},
        {"正在控制'自定义'情景...","Control User-defined scene"},        
        {"版本太低,请升级","Please update the version"},
        {"无配置信息...","No configuration info..."},
        {"确认","Yes"},
        {"取消","No"},
        {"录音","REC"},
        {"防区报警成功","Zone Alarm Succeed"},
        {"防区报警失败","Zone Alarm Failed"},
        {"防区布防","Zone Arm"},
        {"防区报警","Zone Alarm"},
        {"启用防区","Enable Zone"},
        {"禁用防区","Disable Zone"},
        {"防区未布防","Zone Disarm"},
        {"门口机呼叫","Gate Station calling-in"},
        {"小门口机呼叫","Front door station calling-in"},
        {"数字小门口机呼叫","IP Front door station calling-in"},
        {"围墙机呼叫","Entrance station calling-in"},
        {"围墙机","Entrance station"},
        {"区号位数(0-2):","G(0-2):"},
        {"栋号位数(0-3):","B(0-3):"},
        {"单元号位数(0-2):","U(0-2):"},
        {"层号位数(0-3):","F(0-3):"},
        {"房间号位数(0-3):","R(0-3):"},
        {"请按下左上角红色坐标,无触摸20秒后自动退出!","Press the red coordinate,if no touch,exit after 20s."},
        {"请按下右下角红色坐标,无触摸20秒后自动退出!","Press the red coordinate,if no touch,exit after 20s."},
        {"请按下右上角红色坐标,无触摸20秒后自动退出!","Press the red coordinate,if no touch,exit after 20s."},
        {"请按下左下角红色坐标,无触摸20秒后自动退出!","Press the red coordinate,if no touch,exit after 20s."},
      
        {"自定义1","NO.1"},
        {"自定义2","NO.2"},
        {"自定义3","NO.3"},
        {"自定义4","NO.4"},
        {"自定义5","NO.5"},
        {"自定义6","NO.6"},
        {"自定义7","NO.7"},
        {"自动抓拍","Snapshot"},
        {"撤  防","Disarm"},
        //
        {"请选择桌面位置","Select replace desktop icon"},
        {"已存在","Exists"},
        {"设置显示屏7寸屏","Screen size is 7 inch"},
        {"设置显示屏10寸屏","Screen size is 10 inch"},
        {"闹钟响铃中...","Alarm clock rings..."},
        {"延时时间(分钟):","Delay(Min):"},
        {"是否设置延时?按'确定'设置延时,并且设置离家情景,按'取消'则只设置离家情景.","Confirm to set delay? Press 'Yes' to set delay and outside scene,press 'No' just to set outside scene"},
        {"请设置插座延时关闭的时间,按'确认'键确认","Please set delay time,'OK' for confirm"},
        {"存储空间不够，释放存储空间?","Insufficient storage space, please free up additional space"},
        {"释放存储空间...","Free up additional space..."},
        //
        {"未增加闹钟!","No clock!"},
        {"情景编号","NO."},
        {"当前状态:","Status:"},
        {"未知","Unknown"},
        {"获取状态中...","Get status..."},
        {"默认风格","Default style"},
        {"时尚风格","Fashion style"},
        {"新 增","Add"},
        {"查 看","Check"},
        {"电话本","contacts"},
        {"电话本已满","Full phone book"},//翻译
        {"媒体娱乐","Media Service"},//翻译
        {"视频","Video"},//翻译
        {"音乐","Music"},//翻译
        {"U盘","USB"},//翻译
        {"U盘2","USB2"},//翻译
        {"SD卡","SD Card"},//翻译
        {"加载中...","Loading..."},
        {"录像抓拍","Snapshot"},
        {"录像","Video"},
        {"拷贝数据到SD卡...","Copy data to SD Card..."},
        {"拷贝数据到U盘...","Copy data to USB..."},
        {"请选择文件","Please select file"},
   		{"抓拍存储的图片快满，请及时删除","Snap file Warning"},
   		{"录像存储的录像快满，请及时删除","Rec file Warning"},
   		{"你确定要清空所有录像","Clear all videos?"},
        {"你确定要删除该录像","Delete the video?"},
        {"显示错误","Display Error"},
        {"您还未阅读,确定删除?","Confirm to delete?"},
        {"版本一样,无需升级","Same version,no need to upgrade"},
        {"歌名","Title"},
        {"作者","Author"},
        {"专辑名","Album"},
        {"歌名:未知","Title:Unknown"},
        {"作者:未知","Author:Unknown"},
        {"专辑名:未知","Album:Unknown"},
        {"年份","Year"},
        {"未知","Unknown"},
        {"单曲循环","Single Cycle"},
        {"顺序循环","Order Cycle"},
        {"随机循环","Random Cycle"},
        {"视频列表","Video List"},
        {"没有视频","No Video"},
        {"没有音乐","No Music"},
        {"歌曲列表","Music List"},
        {"图片列表","Picture List"},
        {"正在播放","Playing"},
        {"分机ID:","Room ID:"},
        {"命令发送成功","Send order succeeded"},
        {"命令发送失败","Failed to send order"},
        {"请点击校屏点,依次校屏","Screen Calibration"},
        {"控制成功","Control succeeded"},
        {"控制失败","Control failed"},
        {"注册成功","Register Succeeded"},
        {"注册失败","Register Failed"},
        {"特效","Special effects"},
        {"访客呼叫优先","Visitor Priority Call"},
        {"确定重置电平设置!","Confirm reset level!"},
        {"手柄报警","Hnd Alarm"},
        {"梯控","Lift"},
        {"按键报警","Alarm1"},
        {"外接报警","Alarm2"},
        {"手柄开锁","Hnd Unlock"},
        {"手柄摘机","Hnd Holdon"},
        {"门铃","Doorbell"},
        {"呼叫键","Call Key"},
        {"开锁键","Unlock Key"},
        {"对讲键","Holdon Key"},
        {"保存后,需重启设备生效","Please restart device after saved"},
        {"设置有效电平,1-高电平,0-低电平","      Set valid level,1-high,0-low"},
        {"U盘测试","Udisk"},
        {"SD卡测试","SD"},
        {"摄像头","Camera"},
        {"LED灯","LED"},
        {"报警铃音","Alarm Ring"},
        {"探头复位","Det Reset"},
        {"失败","Failed"},
        {"成功","Succeeded"},
        {"测试中","Testing"},
        {"工程配置","Setup"},
        {"端口配置","Port Config"},
        {"监控配置","IPC Config"},
        {"设备已达上限!","Over limit!"},
        {"设备不存在!","Not found!"},
        {"设备号已存在!","Device ID exists!"},
        {"IP已存在!","IP exists"},
        {"操作成功!","Succeeded!"},
        {"IP配置错误!","Failed!"},
        {"中心设置IO电平成功,重启中...","Set IO level succeeded! restart..."},
        {"无线配置","Wifi setting"},
        {"本机","Local"},
        {"副管理机","Sub Guard Station"},
		{"家居网关","Smart Box"},
		{"搜索网关","Search Box"},
		{"搜索中...","Search ..."},
		{"搜索失败","Failed !"},
		{"功能开关","Switch"},
        {"是否启用防拆开关","Anti demolition switch"},
    	{"是否启用WIFI","Enable wifi"}
};


char* GetLocalText(char* text,int ise)
{
        int i = 0;
        for(i = 0; i<sizeof(g_language_res);i++)
        {

                if( (ise == 0) && (strcmp(g_language_res[i].ctext,text) == 0)){
                        if(GetCurrentLanguage() == ENGLISH)
                                return g_language_res[i].etext;
                        return g_language_res[i].ctext;
                }else if((ise == 1) && (strcmp(g_language_res[i].etext,text) == 0)){
                        if(GetCurrentLanguage() == ENGLISH)
                                return g_language_res[i].etext;
                        else if(GetCurrentLanguage() == CHINESE)
                                return g_language_res[i].ctext; //return NULL;
                        return g_language_res[i].ctext;
                }

        }
        return NULL;
}

char* GetLocalText2(char* text)
{
        int i = 0;
        for(i = 0; i<sizeof(g_language_res);i++)
        {

                if((strcmp(g_language_res[i].ctext,text) == 0)){
                        if(GetCurrentLanguage() == ENGLISH)
                                return g_language_res[i].etext;
                        return g_language_res[i].ctext;
                }
                if((strcmp(g_language_res[i].etext,text) == 0)){
                        if(GetCurrentLanguage() == ENGLISH)
                                return g_language_res[i].etext;
                        return g_language_res[i].ctext;
                }

        }
        return NULL;
}
