#============================================
#Makefile for enet
#============================================
#arc-linux
#CC = ccache arc-linux-uclibc-gcc
#AR = arc-linux-uclibc-ar
#STRIP = arc-linux-uclibc-strip

#ARM-LINUX
CC = $(TARGET_TOOLCHAIN)gcc
AR = $(TARGET_TOOLCHAIN)ar
STRIP = $(TARGET_TOOLCHAIN)strip
CXX=$(TARGET_TOOLCHAIN)g++



#linux
#CC = gcc
#AR = ar
#STRIP = strip

CFLAGS =   -D_GNU_SOURCE=1 -D_REENTRANT -Wl
#CXXFLAGS = -shared 
INCLUDE =  -I./include  -I../SDL-1.2.14/include  -I$(TARGET_SDK)

LIBS_TARGET =libSDL_draw.a


LIBS_COBJS= src/Draw_Circle.o\
	src/Draw_Ellipse.o\
	src/Draw_FillCircle.o\
	src/Draw_FillEllipse.o\
	src/Draw_FillRound.o\
	src/Draw_HLine.o\
	src/Draw_Line.o\
	src/Draw_Pixel.o\
	src/Draw_Rect.o\
	src/Draw_Round.o\
	src/Draw_VLine.o\
	src/SDL_draw.o	\

####################################
LD_LIB_PATH += -L../build_lib
LD_SYS_PATH += -L$(TARGET_SYSLIB_PATH)/lib
LD_SYS_PATH += -L$(TARGET_SYSLIB_PATH)/usr/lib

all:$(LIBS_TARGET)

lib: $(LIBS_TARGET)



$(LIBS_CXXOBJS):%.o:%.cpp
	$(CXX) $(CFLAGS) $(INCLUDE) -c $< -o $@
	
$(LIBS_COBJS):%.o:%.c
	$(CC) $(CFLAGS) $(INCLUDE) -c $< -o $@

$(LIBS_TARGET): $(LIBS_COBJS) 
	$(AR) -rcs $@ $^
	cp $(LIBS_TARGET) ../build_lib

clean:
	rm -f *.o $(LIBS_TARGET) $(LIBS_COBJS) 

